version: '3.8'

services:
  
  postgres:
    container_name: trading-chat-postgres
    image: postgres:latest
    hostname: localhost
    ports:
        - 5432:5432
    volumes:
        - /postgres-trading-chat:/var/lib/postgresql/data
    networks:
        - trading-chat-net
    environment:
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  seq:
    container_name: trading-chat-seq
    image: datalust/seq:latest
    hostname: localhost
    ports: 
        - 5341:80
    volumes:
      - /var/log/seq-trading-chat:/data
    networks:
        - trading-chat-net
    environment:
        - ACCEPT_EULA=Y

  rabbitmq:
      container_name: trading-chat-rabbitmq
      image: rabbitmq:3-management
      hostname: localhost
      ports:
          - 5672:5672
          - 15672:1567
      networks:
          - trading-chat-net
      volumes:
          - /rabbitmq-trading-chat:/var/lib/rabbitmq

networks:
  trading-chat-net:
    driver: bridge
