version: '3.8'

services:
  
  api:
    container_name: trading-chat-api
    image: trading-chat-api:latest
    build:
      context: ../.
      dockerfile: ./src/TradingChat.WebApp/Dockerfile
    ports:
        - 5010:8080
    networks:
        - trading-chat-net
    environment:
        - ASPNETCORE_ENVIRONMENT=Internal
    depends_on:
      - postgres
      - seq
      - rabbitmq

  chatbot:
    container_name: trading-chat-bot
    image: trading-chat-bot:latest
    build:
      context: ../.
      dockerfile: ./src/TradingChat.ChatBot/Dockerfile
    ports:
        - 5020:8080
    networks:
        - trading-chat-net
    environment:
        - ASPNETCORE_ENVIRONMENT=Internal
    depends_on:
      - postgres
      - seq
      - rabbitmq

networks:
  trading-chat-net:
    name: docker-compose.env/trading-chat-net
