version: '3.8'

services:
  
  postgres:
    container_name: trading-chat-postgres
    image: postgres:latest
    hostname: localhost
    ports:
        - 5432:5432
    volumes:
        - postgres-data:/var/lib/postgresql/data
    networks:
        - trading-chat-net
    environment:
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  rabbitmq:
      container_name: trading-chat-rabbitmq
      image: rabbitmq:3.11.10-management
      hostname: localhost
      ports:
          - 5672:5672
          - 15672:15672
      networks:
          - trading-chat-net
      volumes:
        - rabbitmq-data:/var/lib/rabbitmq/
        - rabbitmq-log:/var/log/rabbitmq

  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - ./grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - trading-chat-net

  loki:
    image: grafana/loki:2.9.4
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
        - trading-chat-net

  otel-collector:
    image: otel/opentelemetry-collector:0.86.0
    command: [ "--config=/etc/otel-collector.yaml" ]
    volumes:
      - ./otel-collector.yaml:/etc/otel-collector.yaml
    networks:
      - trading-chat-net

  tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
      - ./tempo-data:/tmp/tempo
    ports:
      - "14268"  # jaeger ingest
      - "3200"   # tempo
      - "4317"  # otlp grpc
      - "4318"  # otlp http
      - "9411"   # zipkin
    networks:
      - trading-chat-net

networks:
  trading-chat-net:
    driver: bridge

volumes:
  seq-data:
  postgres-data:
  rabbitmq-data:
  rabbitmq-log:
